name: Docker Image Latest

on:
  push:
    paths:
    - 'Watcher/**'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: https://github.com/thalesgroup-cert/Watcher.git#:Watcher
        push: true
        tags: felix83000/watcher:latest
        labels: ${{ steps.meta.outputs.labels }}
