name: Deploy to GitHub Pages

on:
  push:
    paths:
    - 'Watcher/docs/**'
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./Watcher/docs/_build/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
